# Basics of Numpy and Pandas
### Dr. Tirthajyoti Sarkar, Fremont, CA 94536

---

This notebook discusses basics of two most important Python libraries for data analytics and statistical modeling - `Numpy` and `Pandas`,

### Numpy

---

* Numpy array - from list, special functions
* Array operations
* 2-D arrays
* Indexing and slicing
* Conditional subsetting
* Array-array operations
* Basic linear algebra
    - transpose
    - rank, 
    - dot, 
    - matrix multiplication, 
    - inverse, 
    - singular value decomposition, 
    - eigenvalues and eigenvectors
    - solving linear system of equations

### Pandas

---

* Pandas series
* DataFrame - creation, read from files
* Quick checking DataFrame
* Descriptive stats on DataFrame
* Indexing, slicing, conditional subsetting
* Operations on specific rows/columns

## Numpy array from a Python list
Numpy arrays behave like **true numerical vectors**, not ordinary lists. That's why they are used for all mathematical operations, machine learning algorithms, and as basis of Pandas DataFrame for data analytics.

In [1]:
import numpy as np
lst1=[1,2,3]
array1 = np.array(lst1)

In [2]:
type(lst1)

list

In [3]:
type(array1)

numpy.ndarray

In [4]:
lst2=[10,11,12]
array2 = np.array(lst2)

In [5]:
print(f"Adding two lists {lst1} and {lst2} together: {lst1+lst2}")

Adding two lists [1, 2, 3] and [10, 11, 12] together: [1, 2, 3, 10, 11, 12]


In [6]:
print(f"Adding two numpy arrays {array1} and {array2} together: {array1+array2}")

Adding two numpy arrays [1 2 3] and [10 11 12] together: [11 13 15]


## Mathematical operations with/on Numpy arrays

In [7]:
print("array2 multiplied by array1: ",array1*array2)
print("array2 divided by array1: ",array2/array1)
print("array2 raised to the power of array1: ",array2**array1)

array2 multiplied by array1:  [10 22 36]
array2 divided by array1:  [10.   5.5  4. ]
array2 raised to the power of array1:  [  10  121 1728]


In [8]:
# sine function
print("Sine: ",np.sin(array1))
# logarithm
print("Natural logarithm: ",np.log(array1))
print("Base-10 logarithm: ",np.log10(array1))
print("Base-2 logarithm: ",np.log2(array1))
# Exponential
print("Exponential: ",np.exp(array1))

Sine:  [0.84147098 0.90929743 0.14112001]
Natural logarithm:  [0.         0.69314718 1.09861229]
Base-10 logarithm:  [0.         0.30103    0.47712125]
Base-2 logarithm:  [0.        1.        1.5849625]
Exponential:  [ 2.71828183  7.3890561  20.08553692]


## How to generate arrays easily?
* `np.zeros`
* `np.ones`
* `np.arange`
* `np.linspace`

In [11]:
print("A series of zeroes:",np.zeros(7))
print("A series of ones:",np.ones(9))
print("A series of numbers:",np.arange(5,16,0.5))
print("Numbers spaced apart by 2:",np.arange(0,11,2))
print("Numbers spaced apart by float:",np.arange(0,11,2.5))
print("Every 5th number from 30 in reverse order: ",np.arange(30,-1,-5))
print("11 linearly spaced numbers between 1 and 5: ",np.linspace(1,5,11))

A series of zeroes: [0. 0. 0. 0. 0. 0. 0.]
A series of ones: [1. 1. 1. 1. 1. 1. 1. 1. 1.]
A series of numbers: [ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5
 12.  12.5 13.  13.5 14.  14.5 15.  15.5]
Numbers spaced apart by 2: [ 0  2  4  6  8 10]
Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]
Every 5th number from 30 in reverse order:  [30 25 20 15 10  5  0]
11 linearly spaced numbers between 1 and 5:  [1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]


## Multi-dimensional arrays

In [10]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------


In [11]:
my_tuple = np.array([(1.5,2,3), (4,5,6)])
mat_tuple = np.array(my_tuple)
print (mat_tuple)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


## Dimension, shape, size, and data type of the 2D array

In [12]:
print("Dimension of this matrix: ",mat.ndim,sep='') 
print("Size of this matrix: ", mat.size,sep='') 
print("Shape of this matrix: ", mat.shape,sep='')
print("Data type of this matrix: ", mat.dtype,sep='')

Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


## Zeros, Ones, Random, and Identity Matrices and Vectors

In [13]:
print("Vector of zeros: ",np.zeros(5))
print("Matrix of zeros: ",np.zeros((3,4)))
print("Vector of ones: ",np.ones(4))
print("Matrix of ones: ",np.ones((4,2)))
print("Matrix of 5’s: ",5*np.ones((3,3)))
print("Identity matrix of dimension 2:",np.eye(2))
print("Identity matrix of dimension 4:",np.eye(4))
print("Random matrix of shape (4,3):\n",np.random.randint(low=1,high=10,size=(4,3)))

Vector of zeros:  [0. 0. 0. 0. 0.]
Matrix of zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Vector of ones:  [1. 1. 1. 1.]
Matrix of ones:  [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix of 5’s:  [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
Identity matrix of dimension 2: [[1. 0.]
 [0. 1.]]
Identity matrix of dimension 4: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random matrix of shape (4,3):
 [[6 8 8]
 [6 8 7]
 [4 1 7]
 [4 2 3]]


## Reshaping, Ravel, Min, Max, Sorting

In [14]:
a = np.random.randint(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [15]:
print("\na looks like:\n",a)
print("\nb looks like:\n",b)
print("\nc looks like:\n",c)


a looks like:
 [ 7 69 78 55 67 81  3 52 15 35 33 47 51 19 31 93 94 10 99 48 56 91  3 78
 40 70 46 13 28 58]

b looks like:
 [[[ 7 69 78 55 67]
  [81  3 52 15 35]
  [33 47 51 19 31]]

 [[93 94 10 99 48]
  [56 91  3 78 40]
  [70 46 13 28 58]]]

c looks like:
 [[ 7 69 78 55 67]
 [81  3 52 15 35]
 [33 47 51 19 31]
 [93 94 10 99 48]
 [56 91  3 78 40]
 [70 46 13 28 58]]


In [16]:
b_flat = b.ravel()
print(b_flat)

[ 7 69 78 55 67 81  3 52 15 35 33 47 51 19 31 93 94 10 99 48 56 91  3 78
 40 70 46 13 28 58]


## Indexing and slicing

In [17]:
arr = np.arange(0,11)
print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6])
print("Elements up to 4th index are:", arr[:4])
print("Elements from last backwards are:", arr[-1::-1])
print("3 Elements from last backwards are:", arr[-1:-6:-2])

arr2 = np.arange(0,21,2)
print("New array:",arr2)
print("Elements at 2nd, 4th, and 9th index are:", arr2[[2,4,9]]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4 5]
Elements up to 4th index are: [0 1 2 3]
Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]
3 Elements from last backwards are: [10  8  6]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [18]:
mat = np.random.randint(10,100,15).reshape(3,5)
print("Matrix of random 2-digit numbers\n",mat)

print("\nDouble bracket indexing\n")
print("Element in row index 1 and column index 2:", mat[1][2])

print("\nSingle bracket with comma indexing\n")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n")

print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

print("\nSubsetting sub-matrices\n")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix of random 2-digit numbers
 [[84 38 35 38 27]
 [28 11 56 46 96]
 [32 64 87 53 42]]

Double bracket indexing

Element in row index 1 and column index 2: 56

Single bracket with comma indexing

Element in row index 1 and column index 2: 56

Row or column extract

Entire row at index 2: [32 64 87 53 42]
Entire column at index 3: [38 46 53]

Subsetting sub-matrices

Matrix with row indices 1 and 2 and column indices 3 and 4
 [[46 96]
 [53 42]]
Matrix with row indices 0 and 1 and column indices 1 and 3
 [[38 38]
 [11 46]]


## Conditional subsetting

In [19]:
mat = np.random.randint(10,100,15).reshape(3,5)
print("Matrix of random 2-digit numbers\n",mat)
print ("\nElements greater than 50\n", mat[mat>50])

Matrix of random 2-digit numbers
 [[69 90 74 80 12]
 [77 37 75 16 52]
 [79 22 23 37 73]]

Elements greater than 50
 [69 90 74 80 77 75 52 79 73]


In [20]:
mat>50

array([[ True,  True,  True,  True, False],
       [ True, False,  True, False,  True],
       [ True, False, False, False,  True]])

In [21]:
mat*(mat>50)

array([[69, 90, 74, 80,  0],
       [77,  0, 75,  0, 52],
       [79,  0,  0,  0, 73]])

## Array operations (array-array, array-scalar, universal functions)

In [22]:
mat1 = np.random.randint(1,10,9).reshape(3,3)
mat2 = np.random.randint(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n",mat2)

print("\nAddition\n", mat1+mat2)
print("\nMultiplication\n", mat1*mat2)
print("\nDivision\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n", 3*mat1-2*mat2)

print("\nAddition of a scalar (100)\n", 100+mat1)

print("\nExponentiation, matrix cubed here\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
 [[6 6 9]
 [9 4 5]
 [9 2 9]]

2nd Matrix of random single-digit numbers
 [[4 6 6]
 [9 8 2]
 [9 5 7]]

Addition
 [[10 12 15]
 [18 12  7]
 [18  7 16]]

Multiplication
 [[24 36 54]
 [81 32 10]
 [81 10 63]]

Division
 [[1.5        1.         1.5       ]
 [1.         0.5        2.5       ]
 [1.         0.4        1.28571429]]

Lineaer combination: 3*A - 2*B
 [[10  6 15]
 [ 9 -4 11]
 [ 9 -4 13]]

Addition of a scalar (100)
 [[106 106 109]
 [109 104 105]
 [109 102 109]]

Exponentiation, matrix cubed here
 [[216 216 729]
 [729  64 125]
 [729   8 729]]

Exponentiation, sq-root using pow function
 [[2.44948974 2.44948974 3.        ]
 [3.         2.         2.23606798]
 [3.         1.41421356 3.        ]]


## Basic linear algebra operations

In [23]:
mat1 = np.random.randint(1,10,6).reshape(2,3)
mat2 = np.random.randint(1,10,6).reshape(3,2)
vec1 = np.array([2,3,-2])
vec2 = np.array([1,-1,4])

print("Mat1\n"+"-"*15+"\n",mat1)
print()
print("Mat2\n"+"-"*15+"\n",mat2)
print()
print("Vector 1:",vec1)
print("Vector 2:",vec2)

Mat1
---------------
 [[2 6 8]
 [1 3 9]]

Mat2
---------------
 [[5 8]
 [3 6]
 [2 3]]

Vector 1: [ 2  3 -2]
Vector 2: [ 1 -1  4]


### Transpose

In [24]:
mat1.T

array([[2, 1],
       [6, 3],
       [8, 9]])

### DOT product between vectors

$$ \begin{bmatrix}
2 & 3 & -2
\end{bmatrix}^T. \begin{bmatrix}
1 & -1 & 4
\end{bmatrix}= 2\times 1+3\times (-1) + (-2)\times 4 = 2-3-8=-9 $$

In [25]:
np.dot(vec1,vec2)

-9

In [26]:
np.dot(vec2,vec1)

-9

### DOT product between matrices, or vector with matrix (equivalent to matrix multiplication)

Two methods to do matrix multiplication: `matmult` or `dot` (for 2D arrays)

In [27]:
np.dot(mat1,mat2)

array([[44, 76],
       [32, 53]])

In [28]:
np.dot(mat2,mat1)

array([[ 18,  54, 112],
       [ 12,  36,  78],
       [  7,  21,  43]])

In [29]:
np.matmul(mat1,mat2)

array([[44, 76],
       [32, 53]])

In [30]:
np.dot(vec1,mat2)

array([15, 28])

### Eigenvalues and eigenvectors

In [31]:
mat1 = np.array([[6,8,5],[5,9,-3],[7,-7,2]])
print("Mat1\n"+"-"*15+"\n",mat1)
print()

w,v=np.linalg.eig(mat1)
print("Eigenvalues:\n",w)
print("\n")
print("Eigenvectors:\n",v)

Mat1
---------------
 [[ 6  8  5]
 [ 5  9 -3]
 [ 7 -7  2]]

Eigenvalues:
 [-6. 14.  9.]


Eigenvectors:
 [[ 5.43972467e-01 -7.07106781e-01  4.86664263e-01]
 [-3.35174954e-01 -7.07106781e-01 -3.24442842e-01]
 [-7.69253993e-01 -4.80399466e-16  8.11107106e-01]]


### Singular value decomposition

$$\mathbf{A} = \mathbf{U}.\mathbf{\Lambda}.\mathbf{V}$$

$\text{where } \mathbf{\Lambda}=diag(\lambda) \text{ where } \lambda = \text{singular values}$

In [32]:
A = np.array([[6,8,5],[5,9,-3],[7,-7,2]])
print("Original matrix\n",A)
print("\n")
u,s,v=np.linalg.svd(A,compute_uv=1,full_matrices=True)

print("u:",u)
print("\n")
print("Singular values, s:",s)
print("\n")
print("v:",v)
print("\n")
print ("Reconstruction of A, u*diag(s)*v\n",np.dot(u,np.dot(np.diag(s),v)))

Original matrix
 [[ 6  8  5]
 [ 5  9 -3]
 [ 7 -7  2]]


u: [[-0.68695934  0.37021914 -0.62531964]
 [-0.68784118 -0.05365895  0.72387515]
 [ 0.23443844  0.92739339  0.29151349]]


Singular values, s: [14.61084388 10.11782699  5.1139826 ]


v: [[-0.40517118 -0.91215227 -0.06176209]
 [ 0.83464303 -0.39661987  0.38218279]
 [ 0.37310497 -0.10330015 -0.92202048]]


Reconstruction of A, u*diag(s)*v
 [[ 6.  8.  5.]
 [ 5.  9. -3.]
 [ 7. -7.  2.]]


### Rank of a matrix

In [33]:
A = np.array([[6,8,5],[5,9,-3],[7,-7,2]])
print("Matrix A\n",A)
print("\nRank of A:",np.linalg.matrix_rank(A))

Matrix A
 [[ 6  8  5]
 [ 5  9 -3]
 [ 7 -7  2]]

Rank of A: 3


### Matrix inverse

In [34]:
A = np.array([[6,8,5],[5,9,-3],[7,-7,2]])
print("Matrix A\n",A)
inv_A = np.linalg.inv(A)
print("\nInverse of A\n",inv_A)

Matrix A
 [[ 6  8  5]
 [ 5  9 -3]
 [ 7 -7  2]]

Inverse of A
 [[ 0.00396825  0.06746032  0.09126984]
 [ 0.04100529  0.03042328 -0.05687831]
 [ 0.12962963 -0.12962963 -0.01851852]]


In [35]:
A = np.array([[6,8,5],[3,4,2.5],[7,-7,2]])
print("Matrix A\n",A)

rank_A = np.linalg.matrix_rank(A)
if rank_A!=3:
    print("\nRank of A:",rank_A,"\nExpect trouble next!\n")

inv_A = np.linalg.inv(A)
print("\nInverse of A\n",inv_A)

Matrix A
 [[ 6.   8.   5. ]
 [ 3.   4.   2.5]
 [ 7.  -7.   2. ]]

Rank of A: 2 
Expect trouble next!



LinAlgError: Singular matrix

### Linear equation solving, matrix inverse, linear least suqare
You can directly solve linear system of equations using NumPy writing only one line of code.

Suppose you want to solve the following set of equations for (x,y,z).

$$ 2x + 5y + z = 14 $$

$$ 3x - 2y - z = -1 $$

$$ x - 3y + z = 4 $$

It is easy to see that $(2,1,5)$ are the unique solutions.

In [36]:
A = np.array([[2,5,1],[3,-2,-1],[1,-3,1]])
B = np.array([14,-1,4])

print("Coefficient matrix\n",A)
print("\nConstant vector\n",B)

# Solution
x = np.linalg.solve(A,B)

print("\nThe solutions are:",x)

Coefficient matrix
 [[ 2  5  1]
 [ 3 -2 -1]
 [ 1 -3  1]]

Constant vector
 [14 -1  4]

The solutions are: [2. 1. 5.]


### Solution using $\mathbf{A}^{-1}\mathbf{B}$ formula directly

In [37]:
# Solution using inverse
x = np.matmul(np.linalg.inv(A),B)
print("\nThe solutions are:",x)


The solutions are: [2. 1. 5.]


## Pandas series

In [38]:
import pandas as pd

In [39]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)

Labels: ['a', 'b', 'c']
My data: [10, 20, 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}


In [40]:
s1=pd.Series(data=my_data)
print(s1)

0    10
1    20
2    30
dtype: int64


In [41]:
s2=pd.Series(data=my_data, index=labels)
print(s2)

a    10
b    20
c    30
dtype: int64


In [42]:
s3=pd.Series(arr, labels)
print(s3)

a    10
b    20
c    30
dtype: int32


In [43]:
s4=pd.Series(d)
print(s4)

a    10
b    20
c    30
dtype: int64


## Pandas DataFrame

In [44]:
matrix_data = np.random.randint(1,20,size=20).reshape(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe data frame looks like\n",'-'*45, sep='')
print(df)


The data frame looks like
---------------------------------------------
    W   X   Y   Z
A  13  14   1  17
B   1  18  19  10
C   1  12  19  16
D   4  15  15  14
E  12   7   1  11


In [45]:
d={'a':[10,20],'b':[30,40],'c':[50,60]}
df2=pd.DataFrame(data=d,index=['X','Y'])
print(df2)

    a   b   c
X  10  30  50
Y  20  40  60


## DataFrame can be created reading directly from a CSV or an Excel file

Refer to this article, that I wrote for O'Reily Media's Medium publication, to understand various data sources that can be read in Pandas DataFrame directly.

**[Read in the data in a Pandas DataFrame like an expert](https://medium.com/97-things/read-in-the-data-in-a-pandas-dataframe-like-an-expert-d03058edae98)**

In [46]:
df3 = pd.read_csv("./Data/wine.data.csv")

In [47]:
df3.head()

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

In [48]:
df4 = pd.read_excel("./Data/Height_Weight.xlsx")

In [49]:
df4

Name  Height  Weight       Hometown
0     Ashley     155     140      Palo Alto
1      Robin     145     122        Fremont
2   Priyanka     152     131    Santa Clara
3  Youngchul     167     148      Cupertino
4       Aziz     161     139  San Francisco
5       Zoey     181     190        Hayward

## Quick checking DataFrames
* `.head()`
* `.tail()`
* `.sample()`
* `.info()`
* `.describe()`

In [50]:
df3.head()

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

In [51]:
df3.head(3)

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185

In [52]:
df3.tail(7)

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
171      3    12.77        2.39  2.28               19.5         86   
172      3    14.16        2.51  2.48               20.0         91   
173      3    13.71        5.65  2.45               20.5         95   
174      3    13.40        3.91  2.48               23.0        102   
175      3    13.27        4.28  2.26               20.0        120   
176      3    13.17        2.59  2.37               20.0        120   
177      3    14.13        4.10  2.74               24.5         96   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
171           1.39        0.51                  0.48             0.64   
172           1.68        0.70                  0.44             1.24   
173           1.68        0.61                  0.52             1.06   
174           1.80        0.75                  0.43             1.41   
175           1.59        0.69                  0.43             1.35   
176           1.65        0.68                  0.53             1.46   
177           2.05        0.76                  0.56             1.35   

     Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
171         9.899999  0.57                          1.63      470  
172         9.700000  0.62                          1.71      660  
173         7.700000  0.64                          1.74      740  
174         7.300000  0.70                          1.56      750  
175        10.200000  0.59                          1.56      835  
176         9.300000  0.60                          1.62      840  
177         9.200000  0.61                          1.60      560

In [53]:
df3.sample(5)

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
22       1    13.71        1.86  2.36               16.6        101   
18       1    14.19        1.59  2.48               16.5        108   
173      3    13.71        5.65  2.45               20.5         95   
134      3    12.51        1.24  2.25               17.5         85   
71       2    13.86        1.51  2.67               25.0         86   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
22            2.61        2.88                  0.27             1.69   
18            3.30        3.93                  0.32             1.86   
173           1.68        0.61                  0.52             1.06   
134           2.00        0.58                  0.60             1.25   
71            2.95        2.86                  0.21             1.87   

     Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
22              3.80  1.11                          4.00     1035  
18              8.70  1.23                          2.82     1680  
173             7.70  0.64                          1.74      740  
134             5.45  0.75                          1.51      650  
71              3.38  1.36                          3.16      410

In [54]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
Class                           178 non-null int64
Alcohol                         178 non-null float64
Malic acid                      178 non-null float64
Ash                             178 non-null float64
Alcalinity of ash               178 non-null float64
Magnesium                       178 non-null int64
Total phenols                   178 non-null float64
Flavanoids                      178 non-null float64
Nonflavanoid phenols            178 non-null float64
Proanthocyanins                 178 non-null float64
Color intensity                 178 non-null float64
Hue                             178 non-null float64
OD280/OD315 of diluted wines    178 non-null float64
Proline                         178 non-null int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [55]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
Name        6 non-null object
Height      6 non-null int64
Weight      6 non-null int64
Hometown    6 non-null object
dtypes: int64(2), object(2)
memory usage: 320.0+ bytes


In [56]:
df3.describe().transpose()

count        mean         std     min       25%  \
Class                         178.0    1.938202    0.775035    1.00    1.0000   
Alcohol                       178.0   13.000618    0.811827   11.03   12.3625   
Malic acid                    178.0    2.336348    1.117146    0.74    1.6025   
Ash                           178.0    2.366517    0.274344    1.36    2.2100   
Alcalinity of ash             178.0   19.494944    3.339564   10.60   17.2000   
Magnesium                     178.0   99.741573   14.282484   70.00   88.0000   
Total phenols                 178.0    2.295112    0.625851    0.98    1.7425   
Flavanoids                    178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid phenols          178.0    0.361854    0.124453    0.13    0.2700   
Proanthocyanins               178.0    1.590899    0.572359    0.41    1.2500   
Color intensity               178.0    5.058090    2.318286    1.28    3.2200   
Hue                           178.0    0.957449    0.228572    0.48    0.7825   
OD280/OD315 of diluted wines  178.0    2.611685    0.709990    1.27    1.9375   
Proline                       178.0  746.893258  314.907474  278.00  500.5000   

                                  50%       75%      max  
Class                           2.000    3.0000     3.00  
Alcohol                        13.050   13.6775    14.83  
Malic acid                      1.865    3.0825     5.80  
Ash                             2.360    2.5575     3.23  
Alcalinity of ash              19.500   21.5000    30.00  
Magnesium                      98.000  107.0000   162.00  
Total phenols                   2.355    2.8000     3.88  
Flavanoids                      2.135    2.8750     5.08  
Nonflavanoid phenols            0.340    0.4375     0.66  
Proanthocyanins                 1.555    1.9500     3.58  
Color intensity                 4.690    6.2000    13.00  
Hue                             0.965    1.1200     1.71  
OD280/OD315 of diluted wines    2.780    3.1700     4.00  
Proline                       673.500  985.0000  1680.00

In [57]:
df4.describe()

Height      Weight
count    6.000000    6.000000
mean   160.166667  145.000000
std     12.687264   23.748684
min    145.000000  122.000000
25%    152.750000  133.000000
50%    158.000000  139.500000
75%    165.500000  146.000000
max    181.000000  190.000000

## Basic descriptive statistics on a DataFrame
* `mean()`
* `std()`
* `var()`
* `min()` and `max()`

In [58]:
df3.mean()

Class                             1.938202
Alcohol                          13.000618
Malic acid                        2.336348
Ash                               2.366517
Alcalinity of ash                19.494944
Magnesium                        99.741573
Total phenols                     2.295112
Flavanoids                        2.029270
Nonflavanoid phenols              0.361854
Proanthocyanins                   1.590899
Color intensity                   5.058090
Hue                               0.957449
OD280/OD315 of diluted wines      2.611685
Proline                         746.893258
dtype: float64

In [59]:
df3.std()

Class                             0.775035
Alcohol                           0.811827
Malic acid                        1.117146
Ash                               0.274344
Alcalinity of ash                 3.339564
Magnesium                        14.282484
Total phenols                     0.625851
Flavanoids                        0.998859
Nonflavanoid phenols              0.124453
Proanthocyanins                   0.572359
Color intensity                   2.318286
Hue                               0.228572
OD280/OD315 of diluted wines      0.709990
Proline                         314.907474
dtype: float64

In [60]:
df4.var()

Height    160.966667
Weight    564.000000
dtype: float64

In [61]:
df4.min()

Name           Ashley
Height            145
Weight            122
Hometown    Cupertino
dtype: object

## Indexing, slicing columns and rows of a DataFrame

In [62]:
print("\nThe 'Name' column\n",'-'*25, sep='')
print(df4['Name'])
print("\nType of the column: ", type(df4['Name']), sep='')
print("\nThe 'Name' and 'Weight' columns indexed by passing a list\n",'-'*55, sep='')
print(df4[['Name','Weight']])
print("\nType of the pair of columns: ", type(df4[['Name','Weight']]), sep='')


The 'Name' column
-------------------------
0       Ashley
1        Robin
2     Priyanka
3    Youngchul
4         Aziz
5         Zoey
Name: Name, dtype: object

Type of the column: <class 'pandas.core.series.Series'>

The 'Name' and 'Weight' columns indexed by passing a list
-------------------------------------------------------
        Name  Weight
0     Ashley     140
1      Robin     122
2   Priyanka     131
3  Youngchul     148
4       Aziz     139
5       Zoey     190

Type of the pair of columns: <class 'pandas.core.frame.DataFrame'>


In [63]:
print("\nLabel-based 'loc' method can be used for selecting row(s)\n",'-'*60, sep='')
print("\nSingle row\n")
print(df.loc['C'])
print("\nMultiple rows\n")
print(df.loc[['B','C']])
print("\nIndex position based 'iloc' method can be used for selecting row(s)\n",'-'*70, sep='')
print("\nSingle row\n")
print(df.iloc[2])
print("\nMultiple rows\n")
print(df.iloc[[1,2]])


Label-based 'loc' method can be used for selecting row(s)
------------------------------------------------------------

Single row

W     1
X    12
Y    19
Z    16
Name: C, dtype: int32

Multiple rows

   W   X   Y   Z
B  1  18  19  10
C  1  12  19  16

Index position based 'iloc' method can be used for selecting row(s)
----------------------------------------------------------------------

Single row

W     1
X    12
Y    19
Z    16
Name: C, dtype: int32

Multiple rows

   W   X   Y   Z
B  1  18  19  10
C  1  12  19  16


## Conditional subsetting

In [64]:
df4['Height']>155

0    False
1    False
2    False
3     True
4     True
5     True
Name: Height, dtype: bool

In [65]:
df4[df4['Height']>155]

Name  Height  Weight       Hometown
3  Youngchul     167     148      Cupertino
4       Aziz     161     139  San Francisco
5       Zoey     181     190        Hayward

Which students have a **height more than 155 cm and weigh less than 140 lbs**?

In [66]:
df4[(df4['Height']>155) & (df4['Weight']<140)]

Name  Height  Weight       Hometown
4  Aziz     161     139  San Francisco

## Operations on specific columns/rows

In [67]:
df3.head()

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
0             5.64  1.04                          3.92     1065  
1             4.38  1.05                          3.40     1050  
2             5.68  1.03                          3.17     1185  
3             7.80  0.86                          3.45     1480  
4             4.32  1.04                          2.93      735

#### What is the standard deviation of Magnesium and Ash contents for the wine dataset?

In [68]:
df3[['Magnesium','Ash']].std()

Magnesium    14.282484
Ash           0.274344
dtype: float64

#### What is the range of alcohol content in the wine dataset?

In [69]:
range_alcohol=df3['Alcohol'].max()- df3['Alcohol'].min()
print("The range of alcohol content is: ", round(range_alcohol,3))

The range of alcohol content is:  3.8


#### Top 5 percentile in terms of Flavanoids?

In [70]:
np.percentile(df3['Flavanoids'],95)

3.4975000000000005

In [71]:
df3[df3['Flavanoids']>=3.4975]

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
13       1    14.75        1.73  2.39               11.4         91   
14       1    14.38        1.87  2.38               12.0        102   
18       1    14.19        1.59  2.48               16.5        108   
42       1    13.88        1.89  2.59               15.0        101   
49       1    13.94        1.73  2.27               17.4        108   
52       1    13.82        1.75  2.42               14.0        111   
58       1    13.72        1.43  2.50               16.7        108   
98       2    12.37        1.07  2.10               18.5         88   
121      2    11.56        2.05  3.23               28.5        119   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
13            3.10        3.69                  0.43             2.81   
14            3.30        3.64                  0.29             2.96   
18            3.30        3.93                  0.32             1.86   
42            3.25        3.56                  0.17             1.70   
49            2.88        3.54                  0.32             2.08   
52            3.88        3.74                  0.32             1.87   
58            3.40        3.67                  0.19             2.04   
98            3.52        3.75                  0.24             1.95   
121           3.18        5.08                  0.47             1.87   

     Color intensity   Hue  OD280/OD315 of diluted wines  Proline  
13              5.40  1.25                          2.73     1150  
14              7.50  1.20                          3.00     1547  
18              8.70  1.23                          2.82     1680  
42              5.43  0.88                          3.56     1095  
49              8.90  1.12                          3.10     1260  
52              7.05  1.01                          3.26     1190  
58              6.80  0.89                          2.87     1285  
98              4.50  1.04                          2.77      660  
121             6.00  0.93                          3.69      465

**Show the average alcohol, ash, and magnesium content of the wine brands which rank top 5 percent in terms of flavanoids**

In [72]:
df3[df3['Flavanoids']>=3.4975][['Ash','Alcohol','Magnesium']].mean()

Ash            2.484444
Alcohol       13.623333
Magnesium    104.000000
dtype: float64

## Create a new column as a function of mathematical operations on existing columns

In [73]:
df4

Name  Height  Weight       Hometown
0     Ashley     155     140      Palo Alto
1      Robin     145     122        Fremont
2   Priyanka     152     131    Santa Clara
3  Youngchul     167     148      Cupertino
4       Aziz     161     139  San Francisco
5       Zoey     181     190        Hayward

In [74]:
df4['BMI']=df4['Weight']*0.453592/(df4['Height']/100)**2
df4

Name  Height  Weight       Hometown        BMI
0     Ashley     155     140      Palo Alto  26.432000
1      Robin     145     122        Fremont  26.320202
2   Priyanka     152     131    Santa Clara  25.718729
3  Youngchul     167     148      Cupertino  24.071001
4       Aziz     161     139  San Francisco  24.323633
5       Zoey     181     190        Hayward  26.306425

In [75]:
df4.sort_values(by='BMI')

Name  Height  Weight       Hometown        BMI
3  Youngchul     167     148      Cupertino  24.071001
4       Aziz     161     139  San Francisco  24.323633
2   Priyanka     152     131    Santa Clara  25.718729
5       Zoey     181     190        Hayward  26.306425
1      Robin     145     122        Fremont  26.320202
0     Ashley     155     140      Palo Alto  26.432000

### Use `inplace=True` to make the changes reflected on the original DataFrame

In [76]:
df4

Name  Height  Weight       Hometown        BMI
0     Ashley     155     140      Palo Alto  26.432000
1      Robin     145     122        Fremont  26.320202
2   Priyanka     152     131    Santa Clara  25.718729
3  Youngchul     167     148      Cupertino  24.071001
4       Aziz     161     139  San Francisco  24.323633
5       Zoey     181     190        Hayward  26.306425

In [77]:
df4.sort_values(by='BMI',inplace=True)

In [78]:
df4

Name  Height  Weight       Hometown        BMI
3  Youngchul     167     148      Cupertino  24.071001
4       Aziz     161     139  San Francisco  24.323633
2   Priyanka     152     131    Santa Clara  25.718729
5       Zoey     181     190        Hayward  26.306425
1      Robin     145     122        Fremont  26.320202
0     Ashley     155     140      Palo Alto  26.432000